### ISSUE TITLE
add a feature to select hash generator for build dependency only

### ISSUE THREAD

**Issue by darrenmothersele** [crabby-utils/static_file_util#2]
This crate is currently added to dependencies and build dependencies, like this: 

```
[dependencies]
static_file_util = "0.1"
lazy_static = "1.4"   
mime = "0.3"  

[build-dependencies]
static_file_util = "0.1"
```

The hash generation code that is used in `build.rs` is not needed in the main dependency. So we could add a feature, something like this:

```
[dependencies]
static_file_util = "0.1"
lazy_static = "1.4"  
mime = "0.3"      

[build-dependencies]
static_file_util = { version = "0.1", features = [ "hash" ] }
```

**Comment by darrenmothersele** [comment]
add this in v0.2.0 

Example:

```toml
[dependencies]
static_file_util = "0.2"
lazy_static = "1.4"   # Required dependency for lazy static initialization
mime = "0.3"          # For handling MIME types

[build-dependencies]
static_file_util = { version = "0.2", features = ["process_file"] }
```
